In [8]:
import os
import json
import requests
import pandas as pd
import warnings
from bs4 import BeautifulSoup

warnings.filterwarnings("ignore")
os.makedirs("./BaseInfo", exist_ok=True)
os.makedirs("./Result", exist_ok=True)

# 產業別

In [9]:
# 解碼產業別使用
aa='{"\\u4e0a\\u5e02\\u516c\\u53f8\\u7522\\u696d\\u985e\\u5225":{"1":"\\u6c34\\u6ce5\\u5de5\\u696d","2":"\\u98df\\u54c1\\u5de5\\u696d","3":"\\u5851\\u81a0\\u5de5\\u696d","4":"\\u7d21\\u7e54\\u7e96\\u7dad","5":"\\u96fb\\u6a5f\\u6a5f\\u68b0","6":"\\u96fb\\u5668\\u96fb\\u7e9c","7":"\\u5316\\u5b78\\u5de5\\u696d","8":"\\u751f\\u6280\\u91ab\\u7642\\u696d","9":"\\u73bb\\u7483\\u9676\\u74f7","10":"\\u9020\\u7d19\\u5de5\\u696d","11":"\\u92fc\\u9435\\u5de5\\u696d","12":"\\u6a61\\u81a0\\u5de5\\u696d","13":"\\u6c7d\\u8eca\\u5de5\\u696d","14":"\\u534a\\u5c0e\\u9ad4\\u696d","15":"\\u96fb\\u8166\\u53ca\\u9031\\u908a\\u8a2d\\u5099\\u696d","16":"\\u5149\\u96fb\\u696d","17":"\\u901a\\u4fe1\\u7db2\\u8def\\u696d","18":"\\u96fb\\u5b50\\u96f6\\u7d44\\u4ef6\\u696d","19":"\\u96fb\\u5b50\\u901a\\u8def\\u696d","20":"\\u8cc7\\u8a0a\\u670d\\u52d9\\u696d","21":"\\u5176\\u4ed6\\u96fb\\u5b50\\u696d","22":"\\u5efa\\u6750\\u71df\\u9020","23":"\\u822a\\u904b\\u696d","24":"\\u89c0\\u5149\\u4e8b\\u696d","25":"\\u91d1\\u878d\\u4fdd\\u96aa","26":"\\u8cbf\\u6613\\u767e\\u8ca8","27":"\\u6cb9\\u96fb\\u71c3\\u6c23\\u696d","28":"\\u7d9c\\u5408","29":"\\u5176\\u4ed6","30":"--","31":"--","32":"--","33":"--"},"\\u4e0a\\u6ac3\\u516c\\u53f8\\u7522\\u696d\\u985e\\u5225":{"1":"--","2":"\\u98df\\u54c1\\u5de5\\u696d","3":"\\u5851\\u81a0\\u5de5\\u696d","4":"\\u7d21\\u7e54\\u7e96\\u7dad","5":"\\u96fb\\u6a5f\\u6a5f\\u68b0","6":"\\u96fb\\u5668\\u96fb\\u7e9c","7":"\\u5316\\u5b78\\u5de5\\u696d","8":"\\u751f\\u6280\\u91ab\\u7642\\u696d","9":"\\u73bb\\u7483\\u9676\\u74f7","10":"--","11":"\\u92fc\\u9435\\u5de5\\u696d","12":"\\u6a61\\u81a0\\u5de5\\u696d","13":"--","14":"\\u534a\\u5c0e\\u9ad4\\u696d","15":"\\u96fb\\u8166\\u53ca\\u9031\\u908a\\u8a2d\\u5099\\u696d","16":"\\u5149\\u96fb\\u696d","17":"\\u901a\\u4fe1\\u7db2\\u8def\\u696d","18":"\\u96fb\\u5b50\\u96f6\\u7d44\\u4ef6\\u696d","19":"\\u96fb\\u5b50\\u901a\\u8def\\u696d","20":"\\u8cc7\\u8a0a\\u670d\\u52d9\\u696d","21":"\\u5176\\u4ed6\\u96fb\\u5b50\\u696d","22":"\\u5efa\\u6750\\u71df\\u9020","23":"\\u822a\\u904b\\u696d","24":"\\u89c0\\u5149\\u4e8b\\u696d","25":"\\u91d1\\u878d\\u696d","26":"\\u8cbf\\u6613\\u767e\\u8ca8","27":"\\u6cb9\\u96fb\\u71c3\\u6c23\\u696d","28":"--","29":"\\u5176\\u4ed6","30":"\\u6587\\u5316\\u5275\\u610f\\u696d","31":"\\u8fb2\\u696d\\u79d1\\u6280\\u696d","32":"\\u96fb\\u5b50\\u5546\\u52d9","33":"\\u7ba1\\u7406\\u80a1\\u7968"},"\\u65b0\\u7de8\\u78bc":{"1":"01","2":"02","3":"03","4":"04","5":"05","6":"06","7":"21","8":"22","9":"08","10":"09","11":"10","12":"11","13":"12","14":"24","15":"25","16":"26","17":"27","18":"28","19":"29","20":"30","21":"31","22":"14","23":"15","24":"16","25":"17","26":"18","27":"23","28":"19","29":"20","30":"32","31":"33","32":"34","33":"80"}}'
dd= json.loads(aa)
mappingData=pd.DataFrame.from_dict(dd).dropna()
mappingData=mappingData.dropna()
mappingData['新編碼']=mappingData['新編碼'].apply(lambda x:str(x).zfill(2))
mappingData.loc[len(mappingData.index)] = ['電子工業', '電子工業', '13'] 
mappingData.loc[len(mappingData.index)] = ['綠能環保', '綠能環保', '35'] 
mappingData.loc[len(mappingData.index)] = ['數位雲端', '數位雲端', '36'] 
mappingData.loc[len(mappingData.index)] = ['運動休閒', '運動休閒', '37'] 
mappingData.loc[len(mappingData.index)] = ['居家生活', '居家生活', '38'] 

mappingData.sort_values(by=['新編碼'])

    上市公司產業類別  上櫃公司產業類別 新編碼
1       水泥工業        --  01
2       食品工業      食品工業  02
3       塑膠工業      塑膠工業  03
4       紡織纖維      紡織纖維  04
5       電機機械      電機機械  05
6       電器電纜      電器電纜  06
9       玻璃陶瓷      玻璃陶瓷  08
10      造紙工業        --  09
11      鋼鐵工業      鋼鐵工業  10
12      橡膠工業      橡膠工業  11
13      汽車工業        --  12
33      電子工業      電子工業  13
22      建材營造      建材營造  14
23       航運業       航運業  15
24      觀光事業      觀光事業  16
25      金融保險       金融業  17
26      貿易百貨      貿易百貨  18
28        綜合        --  19
29        其他        其他  20
7       化學工業      化學工業  21
8      生技醫療業     生技醫療業  22
27     油電燃氣業     油電燃氣業  23
14      半導體業      半導體業  24
15  電腦及週邊設備業  電腦及週邊設備業  25
16       光電業       光電業  26
17     通信網路業     通信網路業  27
18    電子零組件業    電子零組件業  28
19     電子通路業     電子通路業  29
20     資訊服務業     資訊服務業  30
21     其他電子業     其他電子業  31
30        --     文化創意業  32
31        --     農業科技業  33
32        --      電子商務  34
34      綠能環保      綠能環保  35
35      數位雲端      數位雲端  36
36      運動休閒      運動休閒  37
37      居家生活      居家生活  38
33        --      管理股票  80

# 上市公司基本資料

In [10]:
# 【上市公司基本資料】
# https://data.gov.tw/dataset/18419

FALLBACK_PATHS = [
    r'BaseInfo/StockBaseData.csv',
    r'Result/StockBaseDataRead.csv',
]

def _load_fallback_listing():
    """從歷史備份檔讀取上市資料"""
    for path in FALLBACK_PATHS:
        try:
            for enc in ['utf-8', 'utf-8-sig', 'big5', 'cp950']:
                try:
                    df = pd.read_csv(path, encoding=enc, dtype=str)
                    df = df[df['Type'] == '上市'].copy()
                    print(f'[上市] 備援讀取成功：{path} ({enc})，共 {len(df)} 筆')
                    return df
                except (UnicodeDecodeError, LookupError):
                    continue
        except FileNotFoundError:
            continue
    print('[上市] 警告：備援檔案也找不到，df_listing2 為空 DataFrame')
    return pd.DataFrame(columns=['公司代號','公司名稱','公司簡稱','產業別','實收資本額','Type','上市公司產業類別','上櫃公司產業類別','新編碼'])

try:
    url = 'https://mopsfin.twse.com.tw/opendata/t187ap03_L.csv'
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36"
    }
    req = requests.get(url, headers=headers, verify=False, timeout=15)
    req.raise_for_status()
    data = req.content.decode('utf8')
    if not data.strip() or '<html' in data.lower():
        raise ValueError('回傳內容非 CSV')
    df_listing = pd.DataFrame([x.replace('"', '').split(',') for x in data.split('\n')])
    df_listing = pd.DataFrame(df_listing.values[1:], columns=df_listing.iloc[0])
    df_listing['Type'] = '上市'
    df_listing1 = df_listing[['公司代號', '公司名稱', '公司簡稱', '產業別', '實收資本額', 'Type']]
    # 解碼產業 / Data 合併
    df_listing2 = pd.merge(df_listing1, mappingData, how='left', left_on='產業別', right_on='新編碼')
    print(f'[上市] 線上抓取成功，共 {len(df_listing2)} 筆')
except Exception as e:
    print(f'[上市] 線上抓取失敗（{e}），改讀備援檔...')
    df_listing2 = _load_fallback_listing()

df_listing2

[上市] 線上抓取失敗（404 Client Error:  for url: https://mopsfin.twse.com.tw/opendata/t187ap03_L.csv），改讀備援檔...
[上市] 備援讀取成功：BaseInfo/StockBaseData.csv (utf-8)，共 1091 筆

      公司代號          公司名稱  公司簡稱  產業別        實收資本額 Type 上市公司產業類別 上櫃公司產業類別  新編碼
0     1101    臺灣水泥股份有限公司    台泥   01  77231817420   上市     水泥工業       --   01
1     1102    亞洲水泥股份有限公司    亞泥   01  35465628810   上市     水泥工業       --   01
2     1103    嘉新水泥股份有限公司    嘉泥   01   7902474590   上市     水泥工業       --   01
3     1104    環球水泥股份有限公司    環泥   01   6866818160   上市     水泥工業       --   01
4     1108    幸福水泥股份有限公司    幸福   01   4047380490   上市     水泥工業       --   01
...    ...           ...   ...  ...          ...  ...      ...      ...  ...
1086  9945  潤泰創新國際股份有限公司   潤泰新   20  28442250860   上市       其他       其他   20
1087  9946    三發地產股份有限公司  三發地產   14   3265541500   上市     建材營造     建材營造   14
1088  9955  佳龍科技工程股份有限公司    佳龍   35   1044358290   上市     綠能環保     綠能環保   35
1089  9958  世紀鋼鐵結構股份有限公司   世紀鋼   10   2468966650   上市     鋼鐵工業     鋼鐵工業   10
1090   NaN           NaN   NaN  NaN          NaN   上市      NaN      NaN  NaN

[1091 rows x 9 columns]

# 上櫃公司基本資料

In [11]:
# 【上櫃公司基本資料】
# UI: https://data.gov.tw/dataset/25036

def _load_fallback_oct():
    """從歷史備份檔讀取上櫃資料"""
    for path in FALLBACK_PATHS:
        try:
            for enc in ['utf-8', 'utf-8-sig', 'big5', 'cp950']:
                try:
                    df = pd.read_csv(path, encoding=enc, dtype=str)
                    df = df[df['Type'] == '上櫃'].copy()
                    print(f'[上櫃] 備援讀取成功：{path} ({enc})，共 {len(df)} 筆')
                    return df
                except (UnicodeDecodeError, LookupError):
                    continue
        except FileNotFoundError:
            continue
    print('[上櫃] 警告：備援檔案也找不到，dfOCT_ 為空 DataFrame')
    return pd.DataFrame(columns=['公司代號','公司名稱','公司簡稱','產業別','實收資本額','Type','上市公司產業類別','上櫃公司產業類別','新編碼'])

try:
    url = 'https://mopsfin.twse.com.tw/opendata/t187ap03_O.csv'
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36"
    }
    req = requests.get(url, headers=headers, verify=False, timeout=15)
    req.raise_for_status()
    data = req.content.decode('utf8')
    if not data.strip() or '<html' in data.lower():
        raise ValueError('回傳內容非 CSV')
    dfOCT = pd.DataFrame([x.replace('"', '').split(',') for x in data.split('\n')])
    dfOCT = pd.DataFrame(dfOCT.values[1:], columns=dfOCT.iloc[0])
    dfOCT['Type'] = '上櫃'
    dfOCT1 = dfOCT[['公司代號', '公司名稱', '公司簡稱', '產業別', '實收資本額', 'Type']]
    # 解碼產業 / Data 合併
    dfOCT_ = pd.merge(dfOCT1, mappingData, how='left', left_on='產業別', right_on='新編碼')
    print(f'[上櫃] 線上抓取成功，共 {len(dfOCT_)} 筆')
except Exception as e:
    print(f'[上櫃] 線上抓取失敗（{e}），改讀備援檔...')
    dfOCT_ = _load_fallback_oct()

dfOCT_

[上櫃] 線上抓取失敗（404 Client Error:  for url: https://mopsfin.twse.com.tw/opendata/t187ap03_O.csv），改讀備援檔...
[上櫃] 備援讀取成功：BaseInfo/StockBaseData.csv (utf-8)，共 889 筆

      公司代號           公司名稱  公司簡稱  產業別       實收資本額 Type 上市公司產業類別 上櫃公司產業類別  新編碼
1091  1240     茂生農經股份有限公司  茂生農經   33   442323730   上櫃       --    農業科技業   33
1092  1259   安心食品服務股份有限公司    安心   16   323895000   上櫃     觀光事業     觀光事業   16
1093  1264     德麥食品股份有限公司    德麥   02   370523670   上櫃     食品工業     食品工業   02
1094  1268     漢來美食股份有限公司  漢來美食   16   422237300   上櫃     觀光事業     觀光事業   16
1095  1294     漢田生技股份有限公司  漢田生技   02   305715630   上櫃     食品工業     食品工業   02
...    ...            ...   ...  ...         ...  ...      ...      ...  ...
1975  9950     萬國通路股份有限公司   萬國通   03  1677160000   上櫃     塑膠工業     塑膠工業   03
1976  9951     皇田工業股份有限公司    皇田   05   733000000   上櫃     電機機械     電機機械   05
1977  9960  邁達康網路事業股份有限公司   邁達康   37   335925000   上櫃     運動休閒     運動休閒   37
1978  9962     有益鋼鐵股份有限公司    有益   10   902202600   上櫃     鋼鐵工業     鋼鐵工業   10
1979   NaN            NaN   NaN  NaN         NaN   上櫃      NaN      NaN  NaN

[889 rows x 9 columns]

# Output & 整合

In [12]:
# output 上市上櫃股票資訊
try:
    _combined = pd.concat([df_listing2, dfOCT_])
    _combined.to_csv(r'BaseInfo/StockBaseData.csv', index=False, encoding='utf-8', errors='ignore')
    _combined.to_csv(r'Result/StockBaseDataRead.csv', index=False, encoding='big5', errors='ignore')
    print(f'[output] 儲存成功，共 {len(_combined)} 筆')
except Exception as e:
    print(f'[output] 儲存失敗：{e}')

_baseInfo = pd.concat([df_listing2, dfOCT_])
_baseInfo = _baseInfo[~_baseInfo['公司代號'].isna()]

df_info = _baseInfo.copy()
print(f'df_info 共 {len(df_info)} 筆，上市：{(df_info["Type"]=="上市").sum()}，上櫃：{(df_info["Type"]=="上櫃").sum()}')
df_info

[output] 儲存成功，共 1980 筆
df_info 共 1978 筆，上市：1090，上櫃：888

      公司代號           公司名稱 公司簡稱 產業別        實收資本額 Type 上市公司產業類別 上櫃公司產業類別 新編碼
0     1101     臺灣水泥股份有限公司   台泥  01  77231817420   上市     水泥工業       --  01
1     1102     亞洲水泥股份有限公司   亞泥  01  35465628810   上市     水泥工業       --  01
2     1103     嘉新水泥股份有限公司   嘉泥  01   7902474590   上市     水泥工業       --  01
3     1104     環球水泥股份有限公司   環泥  01   6866818160   上市     水泥工業       --  01
4     1108     幸福水泥股份有限公司   幸福  01   4047380490   上市     水泥工業       --  01
...    ...            ...  ...  ..          ...  ...      ...      ...  ..
1974  9949       琉園股份有限公司   琉園  32    448607630   上櫃       --    文化創意業  32
1975  9950     萬國通路股份有限公司  萬國通  03   1677160000   上櫃     塑膠工業     塑膠工業  03
1976  9951     皇田工業股份有限公司   皇田  05    733000000   上櫃     電機機械     電機機械  05
1977  9960  邁達康網路事業股份有限公司  邁達康  37    335925000   上櫃     運動休閒     運動休閒  37
1978  9962     有益鋼鐵股份有限公司   有益  10    902202600   上櫃     鋼鐵工業     鋼鐵工業  10

[1978 rows x 9 columns]