In [1]:
import pandas as pd
import dataframe_image as dfi
import requests
import os
import json
import requests
import warnings
from bs4 import BeautifulSoup
os.makedirs("./Result",exist_ok=True)

# 國內成分證券ETF
https://www.twse.com.tw/zh/products/securities/etf/products/domestic.html

In [2]:


url='https://www.twse.com.tw/rwd/zh/ETF/domestic?response=json&_=1681734086399'

headers = {
    "User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36"
}
req = requests.get(url, headers = headers,verify=False)
ETFdata = req.content.decode('utf8')
ETFdf=pd.DataFrame(json.loads(ETFdata)['data'])
ETFdf=ETFdf.dropna()
ETFdf.columns = ['證券代號', '證券簡稱','','']

C:\Users\user\anaconda3\lib\site-packages\urllib3\connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.twse.com.tw'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(


# ETF   持股 Data

In [27]:
# https://www.moneydj.com/ETF/X/Basic/Basic0007A.xdjhtm?etfid=0050.TW
# https://www.moneydj.com/etf/eb/et305001list.djhtm?order=4&c=47
def get_erfBaseData(etfid,rtfdf):
    etfurl='https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid='+etfid+'.TW'
    etfresp = requests.get(etfurl)
    etfresp.encoding = 'utf-8'    #轉換編碼至UTF-8
    print("utl="+etfurl)
    if etfresp.status_code==200 :
        etfsoup = BeautifulSoup(etfresp.text, 'lxml')
        #print(etfsoup.find('table', id="Repeater1").find_all('tr'))
        #印出表格中的所有文字內容
        for tr in etfsoup.find('table', id="Repeater1").find_all('tr'):
            td=tr.find_all('td')
            row = [i.text for i in td]
            row.append(etfid)
            if len(row)>0:
                rtfdf = rtfdf.append([row],ignore_index=True)
        for tr in etfsoup.find('table', id="Repeater2").find_all('tr'):
            td=tr.find_all('td')
            row = [i.text for i in td]
            if len(row)>0:
                row.append(etfid)
                rtfdf = rtfdf.append([row],ignore_index=True)

        rtfdf=rtfdf.dropna()
       
        return rtfdf

In [28]:
rtfdf = pd.DataFrame()
for  etfid in ETFdf['證券代號'].tolist():
    rtfdf=get_erfBaseData(etfid,rtfdf)
# 【Output】   
rtfdf.columns = ['股票名稱', '持股(千股)','比例','增減','ETF_Id']
rtfdf.to_csv(r'BaseInfo/ETFBaseData.csv', index = False, encoding='utf-8', errors='ignore')
rtfdf.to_csv(r'Result/ETFBaseDataRead.csv', index = False,encoding='big5', errors='ignore')

utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=0050.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=0051.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=0050.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=0051.TW

C:\Users\user\AppData\Local\Temp\ipykernel_37072\2110128287.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  rtfdf = rtfdf.append([row],ignore_index=True)
C:\Users\user\AppData\Local\Temp\ipykernel_37072\2110128287.py:23: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  rtfdf = rtfdf.append([row],ignore_index=True)
C:\Users\user\AppData\Local\Temp\ipykernel_37072\2110128287.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  rtfdf = rtfdf.append([row],ignore_index=True)
C:\Users\user\AppData\Local\Temp\ipykernel_37072\2110128287.py:23: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  rtfdf = rtfdf.append([row],ignore_index=True)

utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=0052.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=0052.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=0053.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=0053.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=0055.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=0056.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=0055.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=0056.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=0057.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=0057.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=006203.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=006204.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=006203.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=006204.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=006208.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00690.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=006208.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00690.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00692.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00692.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00701.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00713.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00701.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00713.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00730.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00728.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00730.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00728.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00731.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00731.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00733.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00850.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00733.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00850.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00878.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00881.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00878.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00881.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00891.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00891.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00892.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00894.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00892.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00894.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00896.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00896.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00901.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00900.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00901.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00900.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00904.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00905.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00904.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00905.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00907.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00912.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00907.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00912.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00913.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00913.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00915.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00919.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00915.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00919.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00918.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00918.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00921.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00921.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00923.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00922.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00923.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00922.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00927.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00929.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00927.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00929.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00930.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00932.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00930.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00932.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00934.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00934.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00935.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00936.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00935.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00936.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00939.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00940.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00939.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00940.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00944.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00946.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00944.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00946.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00943.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00943.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00947.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00952.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00947.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00952.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00961.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00961.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00938.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00962.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00938.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00962.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=009803.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=009802.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=009803.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=009802.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=009804.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00980A.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=009804.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00980A.TW

utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=009808.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00982A.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=009808.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00982A.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00981A.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00981A.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00984A.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00984A.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00985A.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00985A.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=009809.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=009809.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00991A.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00991A.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00987A.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00992A.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00987A.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00992A.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00994A.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00994A.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00995A.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=009816.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00995A.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=009816.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00993A.TW
utl=https://www.moneydj.com/ETF/X/Basic/Basic0007a.xdjhtm?etfid=00993A.TW

In [18]:
StockBaseData=pd.read_csv('BaseInfo/StockBaseData.csv')
ETFBaseData=pd.read_csv('BaseInfo/ETFBaseData.csv')

In [19]:
# 兩表Join
df=pd.merge(ETFBaseData, StockBaseData, how='left', left_on='股票名稱', right_on='公司簡稱')
# 處理格式問題
df['ETF_Id']='00'+df['ETF_Id'].astype(str)

#處理上市公司產業類別對應不到的狀況
df['上市公司產業類別']=df['上市公司產業類別'].fillna('未分類')
print(df.columns)

Index(['股票名稱', '持股(千股)', '比例', '增減', 'ETF_Id', '公司代號', '公司名稱', '公司簡稱', '產業別',
       '實收資本額', 'Type', '上市公司產業類別', '上櫃公司產業類別', '新編碼'],
      dtype='object')
Index(['股票名稱', '持股(千股)', '比例', '增減', 'ETF_Id', '公司代號', '公司名稱', '公司簡稱', '產業別',
       '實收資本額', 'Type', '上市公司產業類別', '上櫃公司產業類別', '新編碼'],
      dtype='object')

In [20]:
# 取得 etf 對應持股佔比
df['data']=df.agg(lambda x: f"{x['股票名稱']} ( {x['比例']}%)", axis=1)
df.sort_values('比例', ascending=False)
t=df[['ETF_Id','data']]
t[t['ETF_Id']=='0000713']

       ETF_Id            data
1084  0000713      遠傳 ( 9.7%)
1085  0000713    台灣大 ( 9.06%)
1086  0000713     統一 ( 8.48%)
1087  0000713    玉山金 ( 7.15%)
1088  0000713    華南金 ( 6.25%)
1089  0000713    統一超 ( 5.41%)
1090  0000713  台新新光金 ( 3.24%)
1091  0000713     聯電 ( 2.16%)
1092  0000713     聯強 ( 2.05%)
1093  0000713     亞泥 ( 1.95%)
1094  0000713     超豐 ( 1.86%)
1095  0000713     卜蜂 ( 1.55%)
1096  0000713     文曄 ( 1.33%)
1097  0000713    中信金 ( 1.32%)
1098  0000713     崇越 ( 1.31%)
1099  0000713     寶成 ( 1.24%)
1100  0000713     瑞昱 ( 1.23%)
1101  0000713    永豐金 ( 1.21%)
1102  0000713     致伸 ( 1.21%)
1103  0000713    凱基金 ( 1.19%)
1104  0000713     南寶 ( 1.19%)
1105  0000713    元大金 ( 1.17%)
1106  0000713     華航 ( 1.15%)
1107  0000713     裕民 ( 1.14%)
1108  0000713    長榮航 ( 1.14%)
1109  0000713    群益證 ( 1.06%)
1110  0000713     可成 ( 1.04%)
1111  0000713     華立 ( 1.01%)
1112  0000713    東和鋼鐵 ( 1.0%)
1113  0000713     樺漢 ( 0.99%)
1114  0000713     宏全 ( 0.98%)
1115  0000713    玉晶光 ( 0.96%)
1116  0000713    和泰車 ( 0.93%)
1117  0000713   三陽工業 ( 0.92%)
1118  0000713      大成 ( 0.9%)
1119  0000713    台表科 ( 0.84%)
1120  0000713    中保科 ( 0.84%)
1121  0000713     義隆 ( 0.83%)
1122  0000713    國泰金 ( 0.78%)
1123  0000713     和碩 ( 0.75%)
1124  0000713      新產 ( 0.7%)
1125  0000713    統一實 ( 0.56%)
1126  0000713    富邦金 ( 0.54%)
1127  0000713     豐興 ( 0.54%)
1128  0000713      遠百 ( 0.5%)
1129  0000713     聯詠 ( 0.47%)
1130  0000713     華碩 ( 0.36%)
1131  0000713      群光 ( 0.3%)
1132  0000713     遠雄 ( 0.16%)
1133  0000713     裕融 ( 0.15%)

       ETF_Id            data
1084  0000713      遠傳 ( 9.7%)
1085  0000713    台灣大 ( 9.06%)
1086  0000713     統一 ( 8.48%)
1087  0000713    玉山金 ( 7.15%)
1088  0000713    華南金 ( 6.25%)
1089  0000713    統一超 ( 5.41%)
1090  0000713  台新新光金 ( 3.24%)
1091  0000713     聯電 ( 2.16%)
1092  0000713     聯強 ( 2.05%)
1093  0000713     亞泥 ( 1.95%)
1094  0000713     超豐 ( 1.86%)
1095  0000713     卜蜂 ( 1.55%)
1096  0000713     文曄 ( 1.33%)
1097  0000713    中信金 ( 1.32%)
1098  0000713     崇越 ( 1.31%)
1099  0000713     寶成 ( 1.24%)
1100  0000713     瑞昱 ( 1.23%)
1101  0000713    永豐金 ( 1.21%)
1102  0000713     致伸 ( 1.21%)
1103  0000713    凱基金 ( 1.19%)
1104  0000713     南寶 ( 1.19%)
1105  0000713    元大金 ( 1.17%)
1106  0000713     華航 ( 1.15%)
1107  0000713     裕民 ( 1.14%)
1108  0000713    長榮航 ( 1.14%)
1109  0000713    群益證 ( 1.06%)
1110  0000713     可成 ( 1.04%)
1111  0000713     華立 ( 1.01%)
1112  0000713    東和鋼鐵 ( 1.0%)
1113  0000713     樺漢 ( 0.99%)
1114  0000713     宏全 ( 0.98%)
1115  0000713    玉晶光 ( 0.96%)
1116  0000713    和泰車 ( 0.93%)
1117  0000713   三陽工業 ( 0.92%)
1118  0000713      大成 ( 0.9%)
1119  0000713    台表科 ( 0.84%)
1120  0000713    中保科 ( 0.84%)
1121  0000713     義隆 ( 0.83%)
1122  0000713    國泰金 ( 0.78%)
1123  0000713     和碩 ( 0.75%)
1124  0000713      新產 ( 0.7%)
1125  0000713    統一實 ( 0.56%)
1126  0000713    富邦金 ( 0.54%)
1127  0000713     豐興 ( 0.54%)
1128  0000713      遠百 ( 0.5%)
1129  0000713     聯詠 ( 0.47%)
1130  0000713     華碩 ( 0.36%)
1131  0000713      群光 ( 0.3%)
1132  0000713     遠雄 ( 0.16%)
1133  0000713     裕融 ( 0.15%)

In [21]:
keydata=df.groupby(['ETF_Id','上市公司產業類別'])['data'].apply(','.join).reset_index()
keydata

       ETF_Id  上市公司產業類別                                               data
0      000050       光電業                                       大立光 ( 0.34%)
1      000050     其他電子業             鴻海 ( 3.97%),致茂 ( 0.53%),貿聯-KY ( 0.34%)
2      000050      半導體業  台積電 ( 63.89%),聯發科 ( 3.82%),日月光投控 ( 1.44%),聯電 (...
3      000050      塑膠工業                            南亞 ( 0.55%),台塑 ( 0.29%)
4      000050      汽車工業                                       和泰車 ( 0.22%)
..        ...       ...                                                ...
940  0000995A     電子通路業                                        文曄 ( 0.75%)
941  0000995A    電子零組件業  台達電 ( 5.69%),台光電 ( 4.23%),健策 ( 3.75%),台燿 ( 3.3...
942  0000995A      電機機械                華城 ( 1.1%),中興電 ( 0.05%),瑞智 ( 0.04%)
943  0000995A  電腦及週邊設備業  奇鋐 ( 4.41%),勤誠 ( 2.12%),緯穎 ( 2.12%),宜鼎 ( 0.47%...
944  0000995A      食品工業                                        卜蜂 ( 0.42%)

[945 rows x 3 columns]

       ETF_Id  上市公司產業類別                                               data
0      000050       光電業                                       大立光 ( 0.34%)
1      000050     其他電子業             鴻海 ( 3.97%),致茂 ( 0.53%),貿聯-KY ( 0.34%)
2      000050      半導體業  台積電 ( 63.89%),聯發科 ( 3.82%),日月光投控 ( 1.44%),聯電 (...
3      000050      塑膠工業                            南亞 ( 0.55%),台塑 ( 0.29%)
4      000050      汽車工業                                       和泰車 ( 0.22%)
..        ...       ...                                                ...
940  0000995A     電子通路業                                        文曄 ( 0.75%)
941  0000995A    電子零組件業  台達電 ( 5.69%),台光電 ( 4.23%),健策 ( 3.75%),台燿 ( 3.3...
942  0000995A      電機機械                華城 ( 1.1%),中興電 ( 0.05%),瑞智 ( 0.04%)
943  0000995A  電腦及週邊設備業  奇鋐 ( 4.41%),勤誠 ( 2.12%),緯穎 ( 2.12%),宜鼎 ( 0.47%...
944  0000995A      食品工業                                        卜蜂 ( 0.42%)

[945 rows x 3 columns]

In [22]:
# 取得產業比例排名 by ETF_Id 上市公司產業類別

# 挑選要用的欄位
colList=['ETF_Id','股票名稱', '上市公司產業類別','持股(千股)','比例']
df_=df[colList]
# groupby
g=df_.groupby(['ETF_Id','上市公司產業類別']).sum().reset_index()
# 排序 取前三
#g.sort_values('比例', ascending=False).groupby(['ETF_Id']).head(3).sort_values(['ETF_Id', '比例'], ascending=[True, False])
# 排序(這個對未來比較有彈性)
g['row_numbers'] =g.groupby('ETF_Id')['比例'].rank(ascending=False,method='dense')
g[g['ETF_Id']=='00713']

C:\Users\user\AppData\Local\Temp\ipykernel_37072\2400789445.py:7: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  g=df_.groupby(['ETF_Id','上市公司產業類別']).sum().reset_index()

Empty DataFrame
Columns: [ETF_Id, 上市公司產業類別, 比例, row_numbers]
Index: []

C:\Users\user\AppData\Local\Temp\ipykernel_37072\2400789445.py:7: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  g=df_.groupby(['ETF_Id','上市公司產業類別']).sum().reset_index()

Empty DataFrame
Columns: [ETF_Id, 上市公司產業類別, 比例, row_numbers]
Index: []

In [23]:
#轉成橫的方便看
df1=g[g['row_numbers']==1].merge(keydata,on=['ETF_Id','上市公司產業類別'])
df2=g[g['row_numbers']==2].merge(keydata,on=['ETF_Id','上市公司產業類別'])
df3=g[g['row_numbers']==3].merge(keydata,on=['ETF_Id','上市公司產業類別'])
df_result=df1.merge(df2,on='ETF_Id',suffixes=["","_2"]).merge(df3,on='ETF_Id',suffixes=["","_3"])
df_result = df_result.drop(df_result.filter(regex='row_numbers').columns, axis=1)
df_result

,ETF_Id,上市公司產業類別,比例,data,上市公司產業類別_2,比例_2,data_2,上市公司產業類別_3,比例_3,data_3
0,000050,半導體業,71.80,"台積電 ( 63.89%),聯發科 ( 3.82%),日月光投控 ( 1.44%),聯電 (...",金融保險,8.53,"中信金 ( 1.33%),富邦金 ( 1.12%),國泰金 ( 1.04%),玉山金 ( 0...",電子零組件業,5.44,"台達電 ( 3.48%),台光電 ( 0.72%),國巨* ( 0.63%),健策 ( 0...."
1,000051,半導體業,18.35,"華邦電 ( 4.15%),京元電子 ( 3.59%),力積電 ( 2.38%),創意 ( 2...",電子零組件業,17.48,"欣興 ( 5.36%),金像電 ( 2.51%),華通 ( 1.78%),健鼎 ( 1.78...",電腦及週邊設備業,8.65,"仁寶 ( 1.47%),和碩 ( 1.43%),技嘉 ( 1.34%),英業達 ( 1.23..."
2,000052,半導體業,82.61,"台積電 ( 70.99%),聯發科 ( 4.24%),日月光投控 ( 1.6%),聯電 ( ...",電腦及週邊設備業,5.90,"廣達 ( 1.21%),奇鋐 ( 0.78%),緯創 ( 0.65%),緯穎 ( 0.61%...",其他電子業,5.06,"鴻海 ( 4.41%),貿聯-KY ( 0.38%),可成 ( 0.18%),鴻準 ( 0...."
3,000053,半導體業,69.08,"台積電 ( 56.03%),聯發科 ( 4.05%),日月光投控 ( 1.73%),南亞科 ...",電子零組件業,10.74,"台達電 ( 4.62%),台光電 ( 0.82%),欣興 ( 0.69%),金像電 ( 0....",電腦及週邊設備業,6.41,"廣達 ( 1.32%),緯穎 ( 0.95%),奇鋐 ( 0.68%),光寶科 ( 0.52..."
4,000056,金融保險,25.15,"中信金 ( 4.56%),華南金 ( 3.34%),元大金 ( 3.18%),永豐金 ( 3...",半導體業,23.50,"聯發科 ( 5.3%),聯電 ( 5.01%),日月光投控 ( 3.86%),京元電子 ( ...",電腦及週邊設備業,21.87,"廣達 ( 4.28%),華碩 ( 3.32%),緯創 ( 3.23%),光寶科 ( 3.09..."
...,...,...,...,...,...,...,...,...,...,...
62,0000991A,半導體業,51.95,"台積電 ( 19.14%),南亞科 ( 9.67%),群聯 ( 9.36%),鴻勁 ( 4....",電子零組件業,23.59,"台達電 ( 5.65%),台光電 ( 4.6%),台燿 ( 3.49%),欣興 ( 2.72...",其他電子業,5.48,"貿聯-KY ( 3.49%),漢唐 ( 1.98%),鴻海 ( 0.01%)"
63,0000992A,半導體業,44.92,"台積電 ( 7.68%),群聯 ( 6.06%),旺矽 ( 3.43%),穎崴 ( 3.07...",電子零組件業,19.62,"台達電 ( 4.79%),川湖 ( 3.27%),台光電 ( 3.04%),欣興 ( 2.5...",其他電子業,10.18,"貿聯-KY ( 3.92%),致茂 ( 2.39%),弘塑 ( 1.83%),尖點 ( 0...."
64,0000993A,半導體業,26.49,"台積電 ( 8.03%),聯電 ( 7.89%),聯發科 ( 6.26%),日月光投控 ( ...",電子通路業,8.49,文曄 ( 8.49%),通信網路業,7.37,中華電 ( 7.37%)
65,0000994A,半導體業,54.67,"台積電 ( 21.51%),群聯 ( 6.46%),信驊 ( 4.02%),穎崴 ( 3.9...",電子零組件業,22.67,"台達電 ( 4.69%),欣興 ( 4.15%),台光電 ( 3.55%),華通 ( 2.9...",其他電子業,5.35,"致茂 ( 3.66%),雙鴻 ( 0.93%),弘塑 ( 0.76%)"
66,0000995A,半導體業,31.41,"台積電 ( 9.45%),鴻勁 ( 3.94%),旺矽 ( 3.32%),京元電子 ( 2....",電子零組件業,30.02,"台達電 ( 5.69%),台光電 ( 4.23%),健策 ( 3.75%),台燿 ( 3.3...",電腦及週邊設備業,9.76,"奇鋐 ( 4.41%),勤誠 ( 2.12%),緯穎 ( 2.12%),宜鼎 ( 0.47%..."

,ETF_Id,上市公司產業類別,比例,data,上市公司產業類別_2,比例_2,data_2,上市公司產業類別_3,比例_3,data_3
0,000050,半導體業,71.80,"台積電 ( 63.89%),聯發科 ( 3.82%),日月光投控 ( 1.44%),聯電 (...",金融保險,8.53,"中信金 ( 1.33%),富邦金 ( 1.12%),國泰金 ( 1.04%),玉山金 ( 0...",電子零組件業,5.44,"台達電 ( 3.48%),台光電 ( 0.72%),國巨* ( 0.63%),健策 ( 0...."
1,000051,半導體業,18.35,"華邦電 ( 4.15%),京元電子 ( 3.59%),力積電 ( 2.38%),創意 ( 2...",電子零組件業,17.48,"欣興 ( 5.36%),金像電 ( 2.51%),華通 ( 1.78%),健鼎 ( 1.78...",電腦及週邊設備業,8.65,"仁寶 ( 1.47%),和碩 ( 1.43%),技嘉 ( 1.34%),英業達 ( 1.23..."
2,000052,半導體業,82.61,"台積電 ( 70.99%),聯發科 ( 4.24%),日月光投控 ( 1.6%),聯電 ( ...",電腦及週邊設備業,5.90,"廣達 ( 1.21%),奇鋐 ( 0.78%),緯創 ( 0.65%),緯穎 ( 0.61%...",其他電子業,5.06,"鴻海 ( 4.41%),貿聯-KY ( 0.38%),可成 ( 0.18%),鴻準 ( 0...."
3,000053,半導體業,69.08,"台積電 ( 56.03%),聯發科 ( 4.05%),日月光投控 ( 1.73%),南亞科 ...",電子零組件業,10.74,"台達電 ( 4.62%),台光電 ( 0.82%),欣興 ( 0.69%),金像電 ( 0....",電腦及週邊設備業,6.41,"廣達 ( 1.32%),緯穎 ( 0.95%),奇鋐 ( 0.68%),光寶科 ( 0.52..."
4,000056,金融保險,25.15,"中信金 ( 4.56%),華南金 ( 3.34%),元大金 ( 3.18%),永豐金 ( 3...",半導體業,23.50,"聯發科 ( 5.3%),聯電 ( 5.01%),日月光投控 ( 3.86%),京元電子 ( ...",電腦及週邊設備業,21.87,"廣達 ( 4.28%),華碩 ( 3.32%),緯創 ( 3.23%),光寶科 ( 3.09..."
...,...,...,...,...,...,...,...,...,...,...
62,0000991A,半導體業,51.95,"台積電 ( 19.14%),南亞科 ( 9.67%),群聯 ( 9.36%),鴻勁 ( 4....",電子零組件業,23.59,"台達電 ( 5.65%),台光電 ( 4.6%),台燿 ( 3.49%),欣興 ( 2.72...",其他電子業,5.48,"貿聯-KY ( 3.49%),漢唐 ( 1.98%),鴻海 ( 0.01%)"
63,0000992A,半導體業,44.92,"台積電 ( 7.68%),群聯 ( 6.06%),旺矽 ( 3.43%),穎崴 ( 3.07...",電子零組件業,19.62,"台達電 ( 4.79%),川湖 ( 3.27%),台光電 ( 3.04%),欣興 ( 2.5...",其他電子業,10.18,"貿聯-KY ( 3.92%),致茂 ( 2.39%),弘塑 ( 1.83%),尖點 ( 0...."
64,0000993A,半導體業,26.49,"台積電 ( 8.03%),聯電 ( 7.89%),聯發科 ( 6.26%),日月光投控 ( ...",電子通路業,8.49,文曄 ( 8.49%),通信網路業,7.37,中華電 ( 7.37%)
65,0000994A,半導體業,54.67,"台積電 ( 21.51%),群聯 ( 6.46%),信驊 ( 4.02%),穎崴 ( 3.9...",電子零組件業,22.67,"台達電 ( 4.69%),欣興 ( 4.15%),台光電 ( 3.55%),華通 ( 2.9...",其他電子業,5.35,"致茂 ( 3.66%),雙鴻 ( 0.93%),弘塑 ( 0.76%)"
66,0000995A,半導體業,31.41,"台積電 ( 9.45%),鴻勁 ( 3.94%),旺矽 ( 3.32%),京元電子 ( 2....",電子零組件業,30.02,"台達電 ( 5.69%),台光電 ( 4.23%),健策 ( 3.75%),台燿 ( 3.3...",電腦及週邊設備業,9.76,"奇鋐 ( 4.41%),勤誠 ( 2.12%),緯穎 ( 2.12%),宜鼎 ( 0.47%..."

In [24]:

# export png
df_styled = df_result.style.background_gradient()
df_styled = df_result.style.set_properties(subset=['data','data_2','data_3'], **{'width': '600px'})
dfi.export(df_styled, "Result/mytable.png")

In [25]:
import IPython.display
IPython.display.HTML(df_result.to_html())

In [26]:
df_styled = (
    df_result.style
    .background_gradient()
    .set_properties(subset=['data', 'data_2', 'data_3'], **{'width': '1200px'})
)

dfi.export(df_styled, "Result/mytable.png")